### ISSUE TITLE
Support SQS-compatible services

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/triggermesh#1189]
Originated from https://github.com/triggermesh/triggermesh/issues/235#issuecomment-1289593778:

> I was able to make Yandex SQS message queue work by "cheating" ARN and endpoint URL.
> The actual message queue URL was
> "https://message-queue.api.cloud.yandex.net/b1gif3gpu6l0dn27acms/dj60000000096kre00a3/testq",
> ARN was
> "yrn:yc:ymq:ru-central1:b1gbhh150rlkfglah2e1:testq".
> 
> I specified ARN
> "arn:aws:sqs:ru-central1:dj60000000096kre00a3:testq"
> and endpoint URL
> "https://message-queue.api.cloud.yandex.net/b1gif3gpu6l0dn27acms/"
> to make the result queue URL correct.
>
> Yandex SQS is compatible with Amazon SQS CLI and SDK so I think it should be working here somehow.

Possible actions for us here:

1. Update ARN schema in SQS CRD to include Yandex regexp,
2. Queue URL should be customizable (?)

**Comment by Kaiass** [comment]
Changing regexp seems not enough due to the following reasons:

- Using ARN beginning "yrn:yc:ymq" instead of "arn:aws:sqs" is not working without any error message (even if passed through regexp). So ARN should start with "arn:aws:sqs" or some code changes are needed.
- ARN contains account ID but in Yandex it's a bit more complicated and queue URL uses different ID. Current workaround is to specify this ID in ARN. This workaround is a bit ugly.

From my point of view it would be best to be able specifying queue URL, region and probably service URL, of course with credentials. Since these fields are enough to work with Amazon SDK, any compatible service would work fine even if their naming/structure is far from standard. ARN should be avoided in this case.

Unfortunately I didn't ever worked with Go language (actually touched Kubernetes first time only a week ago) but I'm very interested in learning new things and may try to implement something on my own. TriggeMesh team members seem very nice to me so maybe they can guide me a little bit :)
