### ISSUE TITLE
Add E2E tests for Amazon SQS target

### ISSUE THREAD

**Issue by FranBarrera** [triggermesh/triggermesh#414]

**Comment by antoineco** [comment]
Some notes to help you get started:

- We have a helper to receive messages from a SQS queue in the `test-infra` repo ([here](https://github.com/triggermesh/test-infra/blob/8aabc32839ff0e5a6ca03e00bfb44e0c30492ecd/test/e2e/framework/aws/sqs/sqs.go#L94-L114)). Feel free to migrate it. _I omitted it during the initial migration because it wasn't used in sources tests._
    👉 [Usage example](https://github.com/triggermesh/test-infra/blob/1f018e4e0367915d0140324b4f89a647240ce03c/test/e2e/targets/awseventbridge/main.go#L187-L222)

- We also have a helper that can send a CloudEvent to an internal Kubernetes URL, even if this URL isn't reachable from the Ginkgo tests ([here](https://github.com/triggermesh/test-infra/blob/8aabc32839ff0e5a6ca03e00bfb44e0c30492ecd/test/e2e/framework/cloudevents/cloudevents.go#L59-L87)). Likewise, feel free to migrate it here.
    👉 [Usage example](https://github.com/triggermesh/test-infra/blob/1f018e4e0367915d0140324b4f89a647240ce03c/test/e2e/targets/awseventbridge/main.go#L168-L172)
