### ISSUE TITLE
Add AWS EventBridge target

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/triggermesh#615]
In the case of an on-premises deployment of triggermesh users should be able to send events to AWS eventbridge via an EventBridge target.

This target should not make use of the TriggerMesh Partner source and our SaaS offering.

One should be able to create a custom eventbus:
https://docs.aws.amazon.com/sdk-for-go/api/service/eventbridge/#EventBridge.CreateEventBus

Then send events to that bus:
https://docs.aws.amazon.com/sdk-for-go/api/service/eventbridge/#EventBridge.PutEvents

**Comment by antoineco** [comment]
I think it is already clear, but because the issue description mentions it I feel like this needs to be here: the target is not expected to _create_ the EventBus, but only to _send_ to the event bus provided by the user via the CR's spec.

The use case is:
_As a user, I have an event bus (which I provisioned and configured myself) and want to use TriggerMesh to route data to that event bus._

Rationale: TriggerMesh is currently a data bridge, not a provisioner ("Terraform substitute").
I'm not saying we shouldn't be a provisioner (although I would personally find that absurd) but if we want TriggerMesh to be a provisioner, we should think about the design, open an issue, and orchestrate that across all our existing components instead of mixing it with the addition of a single new target.
