### ISSUE TITLE
Allow setting nodeSelector and affinity

### ISSUE THREAD

**Issue by isaac88** [triggermesh/triggermesh#768]
Right now we're trying to use that event source: https://docs.triggermesh.io/apis/sources/#sources.triggermesh.io/v1alpha1.AWSSQSSource but the POD awssqssource-adapter is not able to be schedule in our kubernetes cluster because we have different tainted node groups and it's require to set the proper tolerations in the POD, so the POD will run on the correct group of nodes.

It'll be really useful to allow setting nodeSelector, tolerations, and affinity on all Pods to accomplish this.
It will be great to have that option available to any CRDs that create pods.

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/ 

Regards

**Comment by antoineco** [comment]
@isaac88 `tolerations` can now be set on all TriggerMesh components.

The feature is currently only available on the `main` branch. Deployment manifests can be found here: https://app.circleci.com/pipelines/github/triggermesh/triggermesh/2083/workflows/e48573bb-bcce-4610-88e0-aaa99541b7b7/jobs/5638/artifacts.
Those are development artifacts, the feature will be "officially" available in the next release of TriggerMesh.

I'm keeping this issue open until we implement support for `nodeSelector` and `affinity`.
Meanwhile, could you please share how you expect to use those two features, just so that I get a better understanding of the use case?

**Comment by sebgoa** [comment]
@mukundjalan can you elaborate on what you would need exactly ? nodeSelector ? affinity ? And for which components ?

Any additional details would help schedule this

cc/ @FranBarrera

**Comment by FranBarrera** [comment]
@mukundjalan @isaac88, we just merge the PR to add support for Affinity, so we now support tolerations, nodeSelector and affinity but nodeSelector and affinity are currently only available on the main branch. Deployment manifests can be found here: https://github.com/triggermesh/triggermesh/suites/12206066321/artifacts/645145411
Those are development artifacts. You can safely deploy them on top of your existing TriggerMesh installation in your test environment, but the feature will only become officially available in the next release of TriggerMesh.

**Comment by isaac88** [comment]
Thanks a lot @FranBarrera @sebgoa
