### ISSUE TITLE
Allow arbitrary data in `adapterOverrides` 

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/triggermesh#847]
The idea is to make `adapterOverrides` structure in all our CRs accept arbitrary data by setting the `additionalProperties` attribute. As a result, we'll significantly reduce the CRD sizes and simplify the process of extending the adapter overrides. 
One important precondition is having [a validation webhook](https://github.com/triggermesh/triggermesh/issues/846) in place to check the overrides structure. Since override attributes are the same for all components, validation can be implemented as a common method for all webhooks.

The first mention is in https://github.com/triggermesh/triggermesh/pull/774#pullrequestreview-949427103

**Comment by antoineco** [comment]
Honest opinion: that sounds like a step backwards to me.

OpenAPI is a solid and fairly standard way to describe - and express constraints for - an API. It makes things explicit and easy to document. It also reduces the dependency on webhooks. Also, you can do extra validations using a webhook even if you have an OpenAPI schema, both aren't incompatible.

I was under the impression that we already added everything we deemed relevant to `adapterOverrides`. What did I miss that justifies throwing part of our effort away? (the schema validation)

If the main goal is to _reduce effort_, why not simply invest a day in writing a Python script that can update all CRDs in batches? (like keep a YAML snippet of the `adapterOverrides` in the tool and let it do the structural replacements of `spec.adapterOverrides`) That would be so much more maintainable.

**Comment by tzununbekov** [comment]
Okay, I see the point in the explicit structure of CRDs. The complexity is my main concern - one small adapter knob requires "thousand-lines PR", which makes this structure a little less appealing for wider usage. If you think that a Python script will both solve the complexity problem and still be in the best-practices field, then I'm fine with that. I'm also fine with leaving the decision and its implementation to the next person who will face the need to extend adapter overrides structure 🙂

**Comment by antoineco** [comment]
I agree that _big and repetitive_ isn't appealing and feels broken. We need to address that and make the process easy.
OpenAPI itself supports external schema references using the `$ref` keyword, but [Kubernetes' implementation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation) doesn't support it in CRD objects, which is the root of the problem here.

I'm not too worried about the _size_ of CRD files. The biggest ones are 16 kB currently, which is roughly a hundred times below the hard limit enforced by Kubernetes. Which is why I think the issue could be addressed with the right developers tooling.
I can submit an example just to validate or invalidate that idea. I remember experimenting with Python and YAML before TIL supported YAML, and it was possible to achieve something useful in [less than 20 lines of code](https://github.com/triggermesh/til/wiki/Output-Format/6dacfd6c17569deac47903b20ed4408a2f8b2536#data-conversion).

We have the same kind of "problem" with `status` by the way, which we duplicate everywhere although it almost always has the exact same structure.

**Comment by tzununbekov** [comment]
Problem solved by adding crd-propagation Python script in #848
