### ISSUE TITLE
Provide options to select protocol (amqp vs wss)

### ISSUE THREAD

**Issue by davidkarlsen** [triggermesh/triggermesh#975]
topic in azureservicebustopicsources is defined on form:
`topicID: /subscriptions/<subId>/resourceGroups/<rgName>/providers/Microsoft.ServiceBus/namespaces/<someNamespace>/topics/<someTopic>`
i.e. no option is exposed to tell if adapter should use amqp or wss (websockets).
SDK supports wss: https://github.com/Azure/azure-sdk-for-go/commit/2db8a3b9837267a02739eac7962be31a9a1d63f2

Thus; CR should expose option (through a protocol field, or through url-style in existing topicID field) to define if protocol should be amqp, or over websockets.

Websockets are enterprise-friendly where http-proxies are used, and where protocol choice is limited.

**Comment by odacremolbap** [comment]
Sounds good.

Let's use this thread to discuss design.

**Comment by JeffNeff** [comment]
I created a draft [PR](https://github.com/triggermesh/triggermesh/pull/1003) to solve this, but I'm not convinced that it is the correct approach to take.

Currently, we require the use of an app registration because we need to make & configure the Subscription(s) required to receive messages from the desired topic(s). 

One approach, the one I took in the aforementioned PR, is to add `sasToken.connectionString` to the spec. If this property is configured then we connect via wss. If not, then we proceed with the connection as per normal. [code ref](https://github.com/triggermesh/triggermesh/blob/69b612732f8d439c4fc40d0b08d873ab0db89984/pkg/sources/adapter/azureservicebussource/adapter.go#L119-L130)

I think this might be a bit confusing for users... but I'm also not having any better ideas on how to structure it. So all ears :)

**Comment by davidkarlsen** [comment]
> I created a draft [PR](https://github.com/triggermesh/triggermesh/pull/1003) to solve this, but I'm not convinced that it is the correct approach to take.
> 
> Currently, we require the use of an app registration because we need to make & configure the Subscription(s) required to receive messages from the desired topic(s).

But this should be possible with SAS tokens too?

> One approach, the one I took in the aforementioned PR, is to add `sasToken.connectionString` to the spec. If this property is configured then we connect via wss. If not, then we proceed with the connection as per normal. [code ref](https://github.com/triggermesh/triggermesh/blob/69b612732f8d439c4fc40d0b08d873ab0db89984/pkg/sources/adapter/azureservicebussource/adapter.go#L119-L130)

Why is the selection of protocol (wss vs amqp/tcp) tied to the auth type (ad vs sas)

> I think this might be a bit confusing for users... but I'm also not having any better ideas on how to structure it. So all ears :)

I think so too.
What if it was structured like this:

```
otherparams
auth
protocol
```

**Comment by JeffNeff** [comment]
```
But this should be possible with SAS tokens too?
```
If it is possible to create subscriptions with only a SAS Token, I'm unaware of this.. We only accepted the app registration before due to this reason.

```
Why is the selection of protocol (wss vs amqp/tcp) tied to the auth type (ad vs sas)
```

Because we need the app registration either way, the only reason to populate the SASToken is if you want to configure the WebSocket connection. 


```
otherparams
auth
protocol
```

The only problem with this structure is the validation that the connectionString was populated if the ws protocol was selected might be a little tricky. other then that Im fine with it.

**Comment by davidkarlsen** [comment]
> ```
> But this should be possible with SAS tokens too?
> ```
> 
> If it is possible to create subscriptions with only a SAS Token, I'm unaware of this.. We only accepted the app registration before due to this reason.

See https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas#shared-access-authorization-policies - it seems this is possible with manage scope.

> 
> ```
> Why is the selection of protocol (wss vs amqp/tcp) tied to the auth type (ad vs sas)
> ```
> 
> Because we need the app registration either way, the only reason to populate the SASToken is if you want to configure the WebSocket connection.

It does not seem like that from current docs on https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas but I could be wrong.

**Comment by JeffNeff** [comment]
mhm... i see mixed things here.. probably i will need to play with it a little. 

Here it states its not supported
<img width="1096" alt="Screen Shot 2022-07-05 at 9 53 19 AM" src="https://user-images.githubusercontent.com/60796676/177368607-61b007f0-fe24-4239-95b3-f384031b1b8d.png">

<img width="617" alt="Screen Shot 2022-07-05 at 9 48 35 AM" src="https://user-images.githubusercontent.com/60796676/177368597-1317864c-fa87-4e1c-aea8-456e566dfc52.png">

and here under `Rights required for Service Bus operations` it states that, with proper rights, it is supported.. so I'm left a little confused, to be honest. 

<img width="579" alt="Screen Shot 2022-07-05 at 9 58 18 AM" src="https://user-images.githubusercontent.com/60796676/177369012-b1ddde62-e14a-4c16-89c0-64ecdfa95f1b.png">


```
It does not seem like that from current docs on https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas but I could be wrong.
```

IF we are able to create the subscription via SASToken then yes, you are right. However, I cannot find any code samples where a subscription is made via a SASToken. I will play with it over the next few days and see if I can get it to work, but to be honest I'm fairly positive that this is not possible.

**Comment by FranBarrera** [comment]
Hey @davidkarlsen we just merge a solution for this issue. We added a new parameter to indicate to use WebSockets, you can check it here: https://github.com/triggermesh/triggermesh/blob/main/config/300-azureservicebustopicsource.yaml#L147-L149

**Comment by davidkarlsen** [comment]
> Hey @davidkarlsen we just merge a solution for this issue. We added a new parameter to indicate to use WebSockets, you can check it here: https://github.com/triggermesh/triggermesh/blob/main/config/300-azureservicebustopicsource.yaml#L147-L149

That looks perfect - I'll give it a go when released and I'm back at work.

**Comment by davidkarlsen** [comment]
Seems to work, but did you figure out the SAS vs service-principal issue? It would be good to avoid service-principals if possible for security reasons.
